<<<<<<< HEAD
# Generated by Django 2.2.9 on 2020-02-05 04:11
=======
# Generated by Django 2.2.9 on 2020-02-05 16:42
>>>>>>> Youbin

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
<<<<<<< HEAD
import taggit.managers
=======
>>>>>>> Youbin


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
<<<<<<< HEAD
        ('taggit', '0003_taggeditem_add_unique_index'),
=======
>>>>>>> Youbin
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('category', models.CharField(choices=[('대외활동', '대외활동'), ('공모전', '공모전'), ('스터디', '스터디'), ('인턴', '인턴'), ('강연', '강연'), ('기타', '기타')], max_length=5, verbose_name='카테고리')),
=======
                ('category', models.CharField(choices=[('대외활동', '대외활동'), ('동아리', '동아리'), ('공모전', '공모전'), ('스터디', '스터디'), ('인턴', '인턴'), ('강연', '강연'), ('자격증', '자격증'), ('기타', '기타')], max_length=255, verbose_name='카테고리')),
>>>>>>> Youbin
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('contents', models.TextField(null=True, verbose_name='내용')),
                ('reference', models.URLField(blank=True, null=True, verbose_name='관련 URL')),
                ('start_date', models.DateField(verbose_name='시작 날짜')),
                ('end_date', models.DateField(verbose_name='종료 날짜')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='대표 이미지')),
<<<<<<< HEAD
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
=======
>>>>>>> Youbin
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
