# Generated by Django 2.2.9 on 2020-02-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='daum',
            field=models.URLField(blank=True, null=True, verbose_name='다음 URL'),
        ),
        migrations.AddField(
            model_name='profile',
            name='github',
            field=models.URLField(blank=True, null=True, verbose_name='깃 URL'),
        ),
        migrations.AddField(
            model_name='profile',
            name='naver',
            field=models.URLField(blank=True, null=True, verbose_name='네이버 URL'),
        ),
        migrations.AddField(
            model_name='profile',
            name='other_url',
            field=models.URLField(blank=True, null=True, verbose_name='기타 URL'),
        ),
        migrations.DeleteModel(
            name='Site',
        ),
    ]
