# Generated by Django 2.2.9 on 2020-02-04 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='프로필사진'),
        ),
    ]
