# Generated by Django 2.2.9 on 2020-02-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0002_auto_20200206_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.TextField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
