# Generated by Django 2.2.9 on 2020-02-04 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myprofile', '0002_auto_20200204_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('대외활동', '대외활동'), ('동아리', '동아리'), ('공모전', '공모전'), ('스터디', '스터디'), ('인턴', '인턴'), ('강연', '강연'), ('기타', '기타')], max_length=5, verbose_name='카테고리')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('contents', models.TextField(null=True, verbose_name='내용')),
                ('reference', models.URLField(blank=True, null=True, verbose_name='관련 URL')),
                ('start_date', models.DateField(verbose_name='시작 날짜')),
                ('end_date', models.DateField(verbose_name='종료 날짜')),
                ('photo', models.ImageField(null=True, upload_to='', verbose_name='대표 이미지')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=10, verbose_name='태그명')),
                ('post', models.ManyToManyField(related_name='tag', to='myprofile.Post')),
            ],
        ),
    ]
