# Generated by Django 2.2.9 on 2020-02-07 06:33

from django.db import migrations, models
import myprofile.utils


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0002_auto_20200207_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=20, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=myprofile.utils.date_upload_to, verbose_name='프로필사진'),
        ),
    ]
