# Generated by Django 2.2.9 on 2020-02-07 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0004_auto_20200206_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='한줄소개'),
        ),
    ]
