# Generated by Django 2.2.9 on 2020-02-05 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0005_auto_20200205_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tag_set',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
