# Generated by Django 2.2.9 on 2020-02-04 05:40

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custom_Group',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group')),
                ('category', models.CharField(choices=[('art', '문화/예술/공연'), ('volunteer', '봉사/사회활동'), ('scholarship', '학술/교양'), ('startup', '창업/취업'), ('language', '어학'), ('physical', '체육'), ('play', '친목'), ('etc', '기타')], max_length=255, verbose_name='카테고리')),
                ('passcode', models.CharField(blank=True, max_length=50, null=True, verbose_name='패스코드')),
                ('is_searchable', models.BooleanField(verbose_name='검색허용')),
            ],
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('대외활동', '대외활동'), ('동아리', '동아리'), ('공모전', '공모전'), ('스터디', '스터디'), ('인턴', '인턴'), ('강연', '강연'), ('기타', '기타')], max_length=255, verbose_name='카테고리')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('contents', models.TextField(null=True, verbose_name='내용')),
                ('reference', models.URLField(blank=True, null=True, verbose_name='관련 URL')),
                ('start_date', models.DateField(verbose_name='시작 날짜')),
                ('end_date', models.DateField(verbose_name='종료 날짜')),
                ('photo', models.ImageField(null=True, upload_to='', verbose_name='대표 이미지')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='', verbose_name='프로필사진')),
                ('department', models.CharField(max_length=100, verbose_name='소속')),
                ('description', models.TextField(max_length=200, null=True, verbose_name='한줄소개')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=10, verbose_name='태그명')),
                ('post', models.ManyToManyField(related_name='tag', to='log_share_search.Post')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(verbose_name='대표 URL')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site', to='log_share_search.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BookMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bookmark', to='log_share_search.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmark', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
