# Generated by Django 2.2.9 on 2020-02-06 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=10)),
                ('department', models.TextField(blank=True, max_length=100, verbose_name='소속')),
                ('description', models.TextField(max_length=200, null=True, verbose_name='한줄소개')),
                ('naver', models.URLField(blank=True, null=True, verbose_name='네이버 URL')),
                ('daum', models.URLField(blank=True, null=True, verbose_name='다음 URL')),
                ('github', models.URLField(blank=True, null=True, verbose_name='깃 URL')),
                ('profile_pic', models.ImageField(upload_to='blog/profile_pic')),
                ('photo', models.ImageField(blank=True, upload_to='blog/%Y/%m/%d')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
