# Generated by Django 2.2.9 on 2020-02-06 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200206_1655'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
