# Generated by Django 2.2.9 on 2020-02-14 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'group_membership',
                'managed': False,
            },
        ),
    ]
