# Generated by Django 2.2.9 on 2020-02-21 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customgroup',
            options={'ordering': ['id'], 'verbose_name_plural': 'groups'},
        ),
    ]
