# Generated by Django 2.2.9 on 2020-02-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customgroup',
            options={'ordering': ['id'], 'verbose_name_plural': 'groups'},
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='access_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='그룹가입코드'),
        ),
    ]
