# Generated by Django 3.0.3 on 2020-02-04 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customgroup',
            name='category',
            field=models.CharField(choices=[('art', '문화/예술/공연'), ('volunteer', '봉사/사회활동'), ('scholarship', '학술/교양'), ('startup', '창업/취업'), ('language', '어학'), ('physical', '체육'), ('play', '친목'), ('etc', '기타')], default='etc', max_length=50, verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='notes',
            field=models.TextField(blank=True, verbose_name='그룹설명'),
        ),
    ]
