# Generated by Django 2.2.9 on 2020-02-21 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_management', '0002_auto_20200220_2226'),
        ('group_management', '0002_auto_20200220_1351'),
    ]

    operations = [
    ]
