# Generated by Django 3.0.3 on 2020-02-05 01:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group_management', '0003_grouprequest'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grouprequest',
            unique_together={('group', 'sender')},
        ),
    ]
